#!/usr/bin/env bash
# observe.sh attach <run-dir> <inventory.json> | detach | stop | phase <name> [detail]
#
# Live Grafana for a bench/scale run (opt-in; run.sh calls this with OBSERVE=1):
#
#   laptop: docker compose (Grafana :3000 + Prometheus :9090 + Alloy)
#      │ forward SSH tunnel  (laptop's :8096 → driver-1's :8096)
#      ▼
#   driver-1: curl-bridge writing every broker's /metrics to files it serves
#             over the PRIVATE network at 2s — zero load on broker hosts.
#
#   ALLOY IS LOCAL, not on driver-1: it outlives the cluster, so a teardown no
#   longer destroys the agent and its write-ahead log, and the only thing that
#   stops between runs is the tunnel. The bridge cannot move with it — the
#   released broker's health server RSTs real Prometheus clients (#364), so it
#   has to be a curl loop inside the private network.
#
#   attach  start local stack (once), start the bridge on driver-1, rewrite
#           Alloy's targets and restart it, open the tunnel
#   detach  close the tunnel (the bridge dies with its server; Alloy idles on)
#   stop    detach + stop the local docker compose stack
#
# Watch at http://localhost:3000 (anonymous admin, demo mqttd dashboards).

set -euo pipefail
. "$(dirname "$0")/lib.sh"

OBS_DIR="$SCALE_DIR/observe"
TUNNEL_PID_FILE="${TMPDIR:-/tmp}/bench-scale-observe-tunnel.pid"

cmd="${1:?usage: observe.sh attach <run-dir> <inventory.json> | detach | stop | phase <name> [detail]}"

stop_tunnel() {
	if [ -f "$TUNNEL_PID_FILE" ]; then
		kill "$(cat "$TUNNEL_PID_FILE")" 2>/dev/null || true
		rm -f "$TUNNEL_PID_FILE"
	fi
}

case "$cmd" in
attach)
	RUN="${2:?run-dir}"
	INVENTORY="${3:?inventory.json}"
	command -v docker >/dev/null || die "docker is not running locally (needed for the Grafana/Prometheus stack)"

	say "observe: starting local Grafana(:3000) + Prometheus(:9090)"
	(cd "$OBS_DIR" && docker compose up -d --quiet-pull 2>/dev/null || docker compose up -d)

	DRIVER_IP=$(driver_pub_ip 0)

	# CURL-BRIDGE (issue #364): the released broker's health server RSTs any
	# client that sends normal request headers — real Prometheus clients cannot
	# scrape it over a network, while curl wins the race. Until the fix ships,
	# a loop on driver-1 curls every broker's /metrics into files that a
	# well-behaved python http.server serves to Alloy. Remove with #364.
	BRIDGE="$RUN/prom-bridge.sh"
	{
		echo '#!/bin/sh'
		echo 'mkdir -p /var/lib/bench-prom'
		echo 'while true; do'
		jq -r '.brokers[] | "  curl -sf --max-time 2 http://\(.health)/metrics -o /var/lib/bench-prom/\(.node_id).tmp && mv /var/lib/bench-prom/\(.node_id).tmp /var/lib/bench-prom/\(.node_id).prom"' "$INVENTORY"
		echo '  sleep 2'
		echo 'done'
	} >"$BRIDGE"
	rscp "$BRIDGE" "root@$DRIVER_IP:/opt/prom-bridge.sh"
	rssh "$DRIVER_IP" "chmod +x /opt/prom-bridge.sh; \
		systemctl reset-failed bench-prom-bridge bench-prom-files 2>/dev/null; \
		systemctl stop bench-prom-bridge bench-prom-files 2>/dev/null; \
		systemd-run --unit bench-prom-bridge /opt/prom-bridge.sh; \
		systemd-run --unit bench-prom-files python3 -m http.server 8096 --directory /var/lib/bench-prom" \
		>/dev/null 2>&1 || true

	# Alloy's targets are this run's brokers, reached through the forward tunnel.
	# host.docker.internal is how the container gets at the tunnel on the
	# operator's loopback. Written into the compose mount (a copy is kept in the
	# run dir for the archive) and picked up by a restart.
	ALLOY_CFG="$OBS_DIR/alloy/config.alloy"
	{
		echo "// Generated by observe.sh for run $(basename "$RUN") — do not edit by hand."
		i=0
		while IFS=$'\t' read -r node_id; do
			echo "prometheus.scrape \"broker_$i\" {"
			echo "  targets         = [{ __address__ = \"host.docker.internal:8096\", instance = \"$node_id\" }]"
			echo "  metrics_path    = \"/$node_id.prom\""
			echo '  scrape_interval = "2s"'
			echo '  scrape_timeout  = "2s"'
			echo '  forward_to      = [prometheus.remote_write.local.receiver]'
			echo '}'
			i=$((i + 1))
		done < <(jq -r '.brokers[].node_id' "$INVENTORY")
		echo 'prometheus.scrape "bench_phase" {'
		echo '  targets         = [{ __address__ = "pushgateway:9091" }]'
		echo '  scrape_interval = "5s"'
		# Alloy's default scrape_timeout (10s) is refused against a 5s interval.
		echo '  scrape_timeout  = "3s"'
		echo '  honor_labels    = true'
		echo '  forward_to      = [prometheus.remote_write.local.receiver]'
		echo '}'
		echo 'prometheus.remote_write "local" {'
		echo '  endpoint { url = "http://prometheus:9090/api/v1/write" }'
		echo '}'
	} >"$ALLOY_CFG"
	cp "$ALLOY_CFG" "$RUN/alloy-config.alloy"

	# The tunnel must exist BEFORE Alloy restarts, or its first scrapes fail and
	# it backs off while the first rung is already running.
	say "observe: opening forward tunnel (laptop:8096 -> driver-1:8096)"
	stop_tunnel
	ssh "${SSH_OPTS[@]}" -o UserKnownHostsFile="$RUN/known_hosts" \
		-N -L 8096:localhost:8096 "root@$DRIVER_IP" &
	echo $! >"$TUNNEL_PID_FILE"

	say "observe: pointing local Alloy at $(jq -r '.brokers | length' "$INVENTORY") broker(s)"
	(cd "$OBS_DIR" && docker compose restart alloy >/dev/null 2>&1) || \
		warn "observe: could not restart the local Alloy container"
	say "observe: live at http://localhost:3000 (dashboards: mqttd)"
	;;
phase)
	# Push the run's current phase so a blank dashboard is never ambiguous.
	# Pushgateway replaces the whole group per push, so the previous phase clears
	# itself and exactly one is ever set. Best-effort by design: a rig run must
	# never fail because the operator's Grafana stack is not up.
	NAME="${2:?usage: observe.sh phase <name> [detail]}"
	DETAIL="${3:-}"
	printf '%s\n' \
		'# TYPE bench_run_phase gauge' \
		"bench_run_phase{phase=\"$NAME\",detail=\"$DETAIL\"} 1" |
		curl -sf --max-time 3 --data-binary @- \
			http://localhost:9091/metrics/job/bench_run >/dev/null 2>&1 || true
	;;
detach)
	stop_tunnel
	say "observe: tunnel closed (the bridge dies with its server; local Alloy idles on)"
	;;
stop)
	stop_tunnel
	(cd "$OBS_DIR" && docker compose down 2>/dev/null) || true
	say "observe: local stack stopped"
	;;
*)
	die "unknown observe command: $cmd"
	;;
esac
