#!/usr/bin/env bash
# Mint the secrets the reference cluster needs, once, before the first `docker compose up`.
#
#   ./bootstrap.sh                 # generates a gossip key + passwords for the sample users
#   ./bootstrap.sh alice bob       # ...for the users you name instead
#
# Writes:
#   secrets/mqttd-swim-key   — the gossip authentication key (ADR 0003)
#   secrets/mqttd-passwd     — Argon2id `username:hash` lines (ADR 0004)
#   secrets/PASSWORDS.txt    — the generated plaintext passwords, so you can hand them out
#
# Does NOT write the cluster PKI. That is minted by the `init` one-shot inside
# `docker compose up` (deploy/compose/init.sh), which needs to be root to hand the
# brokers' uid 65532 readable files — and which drops secrets/ca.pem here afterwards, so
# a client on this host has a trust anchor. Running this script is a precondition for that
# one-shot: it refuses to continue, by name, if these files are missing.
#
# `secrets/` is gitignored. PASSWORDS.txt is yours to distribute and then DELETE; the
# broker never reads it. Nothing here is reversible — losing the passwords means
# re-running for those users, which is the correct property for a credential store.
set -euo pipefail
cd "$(dirname "$0")"

SECRETS="./secrets"
KEY_FILE="$SECRETS/mqttd-swim-key"
PW_FILE="$SECRETS/mqttd-passwd"
PLAIN_FILE="$SECRETS/PASSWORDS.txt"

# The broker binary does the hashing (`--hash-password`). Prefer a local build; fall back
# to the published image so this works on a host with no Rust toolchain.
IMAGE="${MQTTD_IMAGE:-ghcr.io/mbilling/fss-mqtt-broker:latest}"
if [[ -n "${MQTTD_BIN:-}" ]]; then
  hash_password() { printf %s "$2" | "$MQTTD_BIN" --hash-password "$1"; }
  echo "hashing with $MQTTD_BIN"
elif [[ -x ../../target/debug/mqttd ]]; then
  hash_password() { printf %s "$2" | ../../target/debug/mqttd --hash-password "$1"; }
  echo "hashing with ../../target/debug/mqttd"
elif command -v docker >/dev/null 2>&1; then
  hash_password() { printf %s "$2" | docker run --rm -i "$IMAGE" --hash-password "$1"; }
  echo "hashing with $IMAGE"
else
  echo "FATAL: need MQTTD_BIN, a local build, or docker to hash passwords" >&2
  exit 2
fi

USERS=("$@")
if [[ ${#USERS[@]} -eq 0 ]]; then
  # The identities deploy/compose/acl.toml already grants. Change both together.
  USERS=(device-a device-b backend probe)
fi

mkdir -p "$SECRETS"
chmod 700 "$SECRETS"

if [[ -e "$KEY_FILE" ]]; then
  echo "keeping the existing gossip key ($KEY_FILE)"
else
  # 32 bytes, hex — the shape MQTTD_SWIM_KEY_FILE expects. Rotating this key means
  # rotating it on EVERY node: a node with the wrong key cannot join the mesh.
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32 > "$KEY_FILE"
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$KEY_FILE"
    echo >> "$KEY_FILE"
  fi
  chmod 600 "$KEY_FILE"
  echo "wrote $KEY_FILE (gossip authentication key — same key on every node)"
fi

if [[ -e "$PW_FILE" ]]; then
  echo
  echo "$PW_FILE already exists — refusing to overwrite it."
  echo "Add a user without touching the others:"
  echo "  printf %s '<password>' | mqttd --hash-password <username> >> $PW_FILE"
  echo "  docker compose up -d init                          # restage the file for the brokers"
  echo "  docker compose kill -s HUP mqttd-1 mqttd-2 mqttd-3 # reload it in place"
  exit 0
fi

: > "$PW_FILE"
chmod 600 "$PW_FILE"
: > "$PLAIN_FILE"
chmod 600 "$PLAIN_FILE"
{
  echo "# Generated by deploy/compose/bootstrap.sh — hand these out, then DELETE this file."
  echo "# The broker never reads it; only secrets/mqttd-passwd matters."
  echo
} >> "$PLAIN_FILE"

for user in "${USERS[@]}"; do
  if command -v openssl >/dev/null 2>&1; then
    password="$(openssl rand -base64 24 | tr -d '\n')"
  else
    password="$(head -c 18 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  fi
  hash_password "$user" "$password" >> "$PW_FILE"
  printf '%s\t%s\n' "$user" "$password" >> "$PLAIN_FILE"
  echo "  + $user"
done

echo
echo "wrote $PW_FILE ($(wc -l < "$PW_FILE" | tr -d ' ') users, Argon2id)"
echo "wrote $PLAIN_FILE — the plaintext passwords. Distribute, then delete."
echo
echo "Next:"
echo "  docker compose up -d       # a one-shot mints the cluster PKI, then the brokers start"
echo "  docker compose ps          # all three healthy in ~60s"
echo
echo "The listener is TLS 1.3 on 8883 (8884, 8885 for nodes 2 and 3); there is no plaintext"
echo "port. The one-shot writes $SECRETS/ca.pem — use it as the client trust anchor:"
echo "  mosquitto_sub -h 127.0.0.1 -p 8883 --cafile secrets/ca.pem \\"
echo "                -t 'devices/+/up/#' -u backend -P '<password from PASSWORDS.txt>'"
