#!/bin/sh
# Drive cross-node MQTT traffic so the dashboard is populated — on EVERY node, not just a
# fixed few. The node list is injected by the compose file (LOADGEN_NODES, generated by
# demo/scale-cluster.py), so the traffic pattern scales with the cluster:
#  - one always-on clean-session QoS-1 subscriber PER node on `demo/#` (=> connections,
#    subscriptions, publish_delivered, and cross-node interest gossip everywhere),
#  - one persistent (clean-session-off) QoS-1 subscriber on the second node (=> a durable
#    session for the sessions/offline-queue/inflight panels, as before),
#  - QoS-1 publishes rotated across ALL nodes (=> publish_received + peer forwarding on
#    every node) plus a retained message on a rotating node (=> retained_messages),
#  - a short-lived, uniquely-identified connection on a rotating node each round
#    (=> connection churn / accepts on every node).
#
# No `set -e`: a broker failing over must not kill the generator (subscribers and the
# publish loop retry on their own); the old behavior restart-looped the whole container.

NODES="${LOADGEN_NODES:-mqttd-1 mqttd-2 mqttd-3}"
echo "loadgen: waiting for brokers to accept connections... ($NODES)"
for host in $NODES; do
	until mosquitto_pub -h "$host" -p 1883 -t demo/_ready -m ping -q 0 2>/dev/null; do
		sleep 2
	done
done
echo "loadgen: brokers up — generating traffic on every node"

# One clean-session fan-out subscriber per node, each in its own retry loop so a node
# restart or failover only pauses that node's subscriber, never the whole generator.
for host in $NODES; do
	(
		while true; do
			mosquitto_sub -h "$host" -p 1883 -t 'demo/#' -q 1 -i "demo-fan-$host" >/dev/null 2>&1
			sleep 2
		done
	) &
done

# The persistent cross-node subscriber (clean session off => a durable session), kept on
# the second node as before; retry-looped like the others.
PERSIST_HOST=$(echo "$NODES" | awk '{print (NF >= 2) ? $2 : $1}')
(
	while true; do
		mosquitto_sub -h "$PERSIST_HOST" -p 1883 -t 'demo/#' -q 1 -i demo-sub -c >/dev/null 2>&1
		sleep 2
	done
) &

i=0
while true; do
	# Rotate the publisher across every node: each node sees publish_received and
	# forwards to the subscribers on all the others.
	n=0
	for host in $NODES; do
		mosquitto_pub -h "$host" -p 1883 -t "demo/topic" -q 1 \
			-m "msg $i via $host" -i "demo-pub-$n" 2>/dev/null || true
		n=$((n + 1))
	done
	# Retained message on a rotating node.
	rot=$((i % n + 1))
	rhost=$(echo "$NODES" | awk -v k="$rot" '{print $k}')
	mosquitto_pub -h "$rhost" -p 1883 -t demo/retained -q 1 -r \
		-m "retained $i" -i demo-ret 2>/dev/null || true
	# A short-lived, unique connection on the same rotating node (accept churn).
	mosquitto_pub -h "$rhost" -p 1883 -t demo/ping -q 0 -m hi -i "demo-ping-$i" 2>/dev/null || true
	i=$((i + 1))
	sleep 1
done
